### ISSUE TITLE
 Failed to download Bazel This could be a target path issue.

### ISSUE THREAD

**Issue by Kadanza** [menny/bazel-leaf#5]
When I try to just open and sync your example project, I have error

I have Mac Os High Sierra and installed Bazel 

```
Caused by: java.lang.RuntimeException: Failed to download Bazel to /Users/olegBorisenkov/.bazel-leaf/bazel-leaf-master/bazel! This could be a target path issue.
	at com.spotify.gradle.bazel.tasks.DownloadBazelTask.download(DownloadBazelTask.java:119)
	at com.spotify.gradle.bazel.BazelLeafPlugin.checkIsBazelBinaryValid(BazelLeafPlugin.java:234)
	at com.spotify.gradle.bazel.BazelLeafPlugin.apply(BazelLeafPlugin.java:98)
	at com.spotify.gradle.bazel.BazelLeafPlugin.apply(BazelLeafPlugin.java:50)

Caused by: java.net.ConnectException: Operation timed out (Connection timed out)
```

**Comment by menny** [comment]
in local.properties:
`bazel.bin.path=/path/to/bin/bazel`

Replace `/path/to/bin/bazel` with the path to your installed bazel bin.

**Comment by Kadanza** [comment]
I add bazel.bin.path and got new error 

```

Got process exit code 1 when running bazel BazelExec: [/Users/olegBorisenkov/.bazel/bin/bazel, build, --curses=no, --color=no, --experimental_ui=no, --progress_in_terminal_title=no, --symlink_prefix=/Users/olegBorisenkov/Desktop/bazel-leaf-master/build/bazel-build/, //andlib:aarbin, --output_groups=noop, --aspects, build/bazel_aspects/__andlib/get_rule_kind.bzl%print_aspect]

org.gradle.api.ProjectConfigurationException: A problem occurred configuring project ':andlib'.
	
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.RuntimeException: java.io.IOException: Got process exit code 1 when running bazel BazelExec: [/Users/olegBorisenkov/.bazel/bin/bazel, build, --curses=no, --color=no, --experimental_ui=no, --progress_in_terminal_title=no, --symlink_prefix=/Users/olegBorisenkov/Desktop/bazel-leaf-master/build/bazel-build/, //andlib:aarbin, --output_groups=noop, --aspects, build/bazel_aspects/__andlib/get_rule_kind.bzl%print_aspect]
	at com.spotify.gradle.bazel.AspectRunner.getAspectResult(AspectRunner.java:57)
	at com.spotify.gradle.bazel.BazelLeafPlugin.configurePlugin(BazelLeafPlugin.java:123)
	at org.gradle.internal.event.BroadcastDispatch$ActionInvocationHandler.dispatch(BroadcastDispatch.java:91)
	at org.gradle.internal.event.BroadcastDispatch$ActionInvocationHandler.dispatch(BroadcastDispatch.java:80)
	at org.gradle.internal.event.AbstractBroadcastDispatch.dispatch(AbstractBroadcastDispatch.java:42)
	at org.gradle.internal.event.BroadcastDispatch$SingletonDispatch.dispatch(BroadcastDispatch.java:230)
	at org.gradle.internal.event.BroadcastDispatch$SingletonDispatch.dispatch(BroadcastDispatch.java:149)
	at org.gradle.internal.event.AbstractBroadcastDispatch.dispatch(AbstractBroadcastDispatch.java:58)
	at org.gradle.internal.event.BroadcastDispatch$CompositeDispatch.dispatch(BroadcastDispatch.java:324)
	at org.gradle.internal.event.BroadcastDispatch$CompositeDispatch.dispatch(BroadcastDispatch.java:234)
	at org.gradle.internal.event.ListenerBroadcast.dispatch(ListenerBroadcast.java:140)
	at org.gradle.internal.event.ListenerBroadcast.dispatch(ListenerBroadcast.java:37)
	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)
	at com.sun.proxy.$Proxy32.afterEvaluate(Unknown Source)
	at org.gradle.configuration.project.LifecycleProjectEvaluator$1.execute(LifecycleProjectEvaluator.java:83)
	at org.gradle.configuration.project.LifecycleProjectEvaluator$1.execute(LifecycleProjectEvaluator.java:80)
	at org.gradle.api.internal.project.DefaultProject.stepEvaluationListener(DefaultProject.java:1393)
	at org.gradle.configuration.project.LifecycleProjectEvaluator.notifyAfterEvaluate(LifecycleProjectEvaluator.java:80)
	... 92 more
Caused by: java.io.IOException: Got process exit code 1 when running bazel BazelExec: [/Users/olegBorisenkov/.bazel/bin/bazel, build, --curses=no, --color=no, --experimental_ui=no, --progress_in_terminal_title=no, --symlink_prefix=/Users/olegBorisenkov/Desktop/bazel-leaf-master/build/bazel-build/, //andlib:aarbin, --output_groups=noop, --aspects, build/bazel_aspects/__andlib/get_rule_kind.bzl%print_aspect]
	at com.spotify.gradle.bazel.utils.BazelExecHelper$BazelExec.start(BazelExecHelper.java:55)
	at com.spotify.gradle.bazel.AspectRunner.getAspectResult(AspectRunner.java:55)
	... 109 more
```
